version: '3.8'
services:
  app-front:
    build:
      context: ./squizz-front
      target: dev
    volumes:
      - ./squizz-front:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
  app-api:
    build:
      context: ./squizz-api
    volumes:
      - ./squizz-api:/app
      - /app/node_modules
    ports:
      - "4001:4001"
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"